id: GAGlobalSnippet
key: GAGlobalSnippet
name: GoogleAnalytics Global Snippet
version: 0.1
description:  <__trans phrase="Google Anaritics global snippet functiontag">
author_name: maRk
author_link: http://labs.markdiary.com/
doc_link: http://www.markdiary.com/docs/

blog_config_template: conf.tmpl
settings:
    mdcGAProfile:
        Default: ''
        Scope: blog
    mdcGADomain:
        Default: 'auto'
        Scope: blog
    mdcGACustom:
        Default: ''
        Scope: blog
l10n_lexicon:
    ja: l10n_ja.yaml
tags:
    function:
        GAGlobalSnippet: $GAGlobalSnippet::GAGlobalSnippet::Tags::_hdlr_google_analytics
